#
# Copyright (c) 1983 Regents of the University of California.
# All rights reserved.  The Berkeley software License Agreement
# specifies the terms and conditions for redistribution.
#
#	@(#)Makefile	6.4 (Berkeley) 6/6/87
#

.PATH:	${.CURDIR}/net/named
#SRCS+=	gethnamadr.c
SRCS+=  sethostent.c
