#
# Public Domain.  1999/2/19 - Steven Schultz
#
#	@(#)Makefile	1.2 (2.11BSD) 1999/2/19
#

.include <bsd.own.mk>

WARNS?=  3

PROG= 	acctd
SRCS= 	acctd.c
MAN=	acctd.8
BINDIR=	/usr/libexec

BINOWN=		root
BINMODE=	700
	
.include <bsd.prog.mk>
# DO NOT DELETE THIS LINE -- mkdep uses it.
# DO NOT PUT ANYTHING AFTER THIS LINE, IT WILL GO AWAY.
