#	$NetBSD: Makefile,v 1.14 2002/09/18 08:12:31 lukem Exp $
#	from: @(#)Makefile	8.1 (Berkeley) 6/8/93

NOOBJ=	# defined

FILES=	3101 aa aed512 beehive diablo dtc382 ibm3101 std stdcrt \
	tandem653 teleray vt100 wyse-adds xerox1720 xerox1730 \
	xerox1730-lm zenith29
FILESDIR= ${BINDIR}/termcap/tabset

.include <bsd.prog.mk>
