#include <sys/param.h>
#include <sys/exec_elf.h>

#define	ELF_NOTE_211BSD_NAMESZ		ELF_NOTE_211BSD_NAMESZ
#define	ELF_NOTE_211BSD_DESCSZ		ELF_NOTE_211BSD_DESCSZ
#define	ELF_NOTE_TYPE_211BSD_TAG	ELF_NOTE_TYPE_211BSD_TAG
#define	ELF_NOTE_211BSD_NAME		ELF_NOTE_211BSD_NAME
#define	__211BSD_Version__			__211BSD_Version__

#define	ELF_NOTE_PAX_NAMESZ			ELF_NOTE_PAX_NAMESZ
#define	ELF_NOTE_PAX_DESCSZ			ELF_NOTE_PAX_DESCSZ
#define	ELF_NOTE_TYPE_PAX_TAG		ELF_NOTE_TYPE_PAX_TAG
#define	ELF_NOTE_PAX_NAME			ELF_NOTE_PAX_NAME
