# $FreeBSD$

INCSDIR= 	/usr/include/stand/boot/common

SRCS+=		subs.c cmds.c logo_beastie.c logo_fred.c

INCS=		boot2.h bootstrap.h commands.h dev_net.h isapnp.h paths.h	\
			rbx.h smbios.h

.include <bsd.kinc.mk>