#	$NetBSD: Makefile.inc,v 1.2 2003/07/04 06:05:30 tshiozak Exp $

.PATH: ${ARCHDIR}/citrus ${.CURDIR}/citrus

SRCS+=	citrus_ctype.c citrus_stdenc.c


#SRCS+= citrus_ctype.c citrus_db_hash.c citrus_frune.c 		\
#		citrus_hash.c citrus_iconv_std.c citrus_iconv.c 	\
#		citrus_memstream.c citrus_mmap.c citrus_stdenc.c
