#	$211BSD: Makefile,v 1.0 2021/05/25 23:59:27 Exp $

INCSDIR= 	/usr/include/vm/include

INCS+= 		device_pager.h pmap.h swap_pager.h vm_extern.h 	\
			vm_inherit.h vm_kern.h vm_mac.h vm_map.h		\ 
			vm_object.h vm_page.h vm_pageout.h vm_pager.h	\
			vm_param.h vm_prot.h vm.h vnode_pager.h
			
INCS+=		vm_amap.h vm_anon.h vm_aobject.h vm_segment.h 	\
			vm_swap.h 
			
			#vm_text.h	
		
.include <bsd.kinc.mk>
