#	$211BSD: Makefile,v 1.0 2021/05/25 23:59:27 Exp $

INCSDIR= 	/usr/include/vm/include

INCS= 		device_pager.h pmap.h swap_pager.h vm_extern.h 	\
			vm_inherit.h vm_kern.h vm_mac.h vm_map.h		\ 
			vm_object.h vm_page.h vm_pageout.h vm_pager.h	\
			vm_param.h vm_prot.h vm_systm.h vm.h 			\
			vnode_pager.h 
		
.include <bsd.kinc.mk>