all:
	for i in libutf libfmt libbio libregexp lib9 mk; do (cd $$i; make); done; ls -l mk/mk

clean:
	for i in libutf libfmt libbio libregexp lib9 mk; do (cd $$i; make clean); done

install:
	for i in libutf libfmt libbio libregexp lib9 mk; do (cd $$i; make install); done



