#
# Copyright (c) 1985 Regents of the University of California.
# All rights reserved.  The Berkeley software License Agreement
# specifies the terms and conditions for redistribution.
#
#	@(#)Makefile	5.1 (Berkeley) 8/9/85
#
# Make a Yacc library
#
NOPIC=		# defined

LIB=		y
SRCS=		libmai.c libzer.c.c

.include <bsd.lib.mk>