#	@(#)Makefile	4.2	6/5/85
#
SCCSID = "@(#)Makefile 4.2 6/5/85"

.include <bsd.own.mk>

LIB=		om
WARNS?=		5

CPPFLAGS+=	-I${.CURDIR}

SRCS=		asin.c atan.c hypot.c jn.c j0.c j1.c pow.c gamma.c 			\
			log.c sin.c sqrt.c tan.c tanh.c sinh.c erf.c exp.c floor.c
INCSDIR=	/usr/include

.include <bsd.lib.mk>