#	$NetBSD: Makefile,v 1.86 2020/05/18 21:19:35 jmcneill Exp $

.include <bsd.own.mk>

SUBDIR=	arch dev fs miscfs 				\
		net net80211 netinet netinet6 	\
		netipsec netkey netns netpfil	\
		sys ufs vm

.include <bsd.kinc.mk>
