#	$NetBSD: Makefile,v 1.86 2020/05/18 21:19:35 jmcneill Exp $

.include <bsd.own.mk>

SUBDIR=	arch crypto dev fs miscfs 		\
		net net80211 netinet netinet6 	\
		netipsec netkey netmpls netns 	\
		nfs sys ufs vm

SUBDIR+= ovl

.include <bsd.kinc.mk>
