#	$NetBSD: Makefile,v 1.292 2021/04/25 23:43:48 christos Exp $
#	from: @(#)Makefile	5.25.1.1 (Berkeley) 5/7/91
#
# Copyright (c) 1980 Regents of the University of California.
# All rights reserved.  The Berkeley software License Agreement
# specifies the terms and conditions for redistribution.
#
#	@(#)Makefile	5.4.1 (2.11BSD) 1996/1/11
#

.include <bsd.own.mk>

SUBDIR= 	libbz2 libcurses libdbm libedit libexecinfo libform libkvm 		\
			libm libmenu libmp libom libpanel libpci libresolv libstubs		\
			libtermcap libutil libvmf liby libz libpthread libpthread_dbg					

.include <bsd.subdir.mk>
