#
# Copyright (c) 1983 Regents of the University of California.
# All rights reserved.  The Berkeley software License Agreement
# specifies the terms and conditions for redistribution.
#
#	@(#)Makefile	5.12.3 (2.11BSD GTE) 1996/12/13
#
# Subdirectories whose routines are included in the making of the
# master tags file (/usr/lib/tags); the Fortran libraries should
# be on this list.
#

# Programs that live in subdirectories, and have makefiles of their own.
#
# 2.11BSD XXX - Libpc isn't important till someone - if ever - ports
# the 4.3BSD version of ucb/pascal.
#

.include <bsd.own.mk>

SUBDIR= libdbm libmp libom libterminfo libutil libvmf liby 

#libcurses

.include <bsd.buildinstall.mk>
.include <bsd.subdir.mk>