#	$211BSD: Makefile,v 1.0 2022/01/23 23:59:27 Exp $

INCSDIR= 	/usr/include/ovl/include

INCS= 		overlay_pager.h ovl_extern.h ovl_map.h ovl_object.h \
			ovl_overlay.h ovl_page.h ovl_segment.h ovl.h pmap.h
		
.include <bsd.kinc.mk>