# $FreeBSD$

.include <bsd.own.mk>

.if (${SA_USE_BCACHE} == "yes")
CPPFLAGS+= -DUSE_BCACHE
.endif

SRCS+= boot.c console.c commands.c disk.c fileload.c \
SRCS+= interp_backslash.c interp_parse.c interp.c
SRCS+= interp_${SA_LOADER_INTERP_NAME}.c
SRCS+= load_exec.c load_ksyms.c metadata.c misc.c

.include <bsd.kinc.mk>