# $FreeBSD$

.include <bsd.own.mk>

SRCS+= boot.c console.c commands.c disk.c fileload.c
SRCS+= interp_backslash.c interp_parse.c interp.c
SRCS+= load_exec.c load_ksyms.c metadata.c misc.c
SRCS+= smbios.c

.if ${LOADER_INTERP} == "dloader"
SRCS+= interp_dloader.c
.elif ${LOADER_INTERP} == "simp"
SRCS+=	interp_simple.c
.else
.error Unknown interpreter ${LOADER_INTERP}
.endif

# Machine-independant ISA PnP
.if ${HAVE_ISABUS} == "yes"
SRCS+=	isapnp.c
.endif

.if ${HAVE_PNP} == "yes"
SRCS+=	pnp.c
.endif

.include <bsd.kinc.mk>