# $FreeBSD$

.include <bsd.own.mk>

SRCS+= boot.c console.c commands.c disk.c fileload.c
SRCS+= interp_backslash.c interp_parse.c interp.c
SRCS+= load_exec.c load_ksyms.c metadata.c misc.c

.if ${LOADER_INTERP} == "dloader"
SRCS+= interp_dloader.c
.elif ${LOADER_INTERP} == "simp"
SRCS+=	interp_simple.c
.else
.error Unknown interpreter ${LOADER_INTERP}
.endif

.include <bsd.kinc.mk>