#	$211BSD: Makefile,v 1.0 2021/05/25 23:59:27 Exp $

INCSDIR= 	/usr/include/netinet

INCS=		icmp_var.h if_ether.h igmp_var.h igmp.h in_pcb.h	\
			in_systm.h in_var.h in.h tcp_debug.h tcp_fsm.h 		\
			tcp_seq.h tcp_timer.h tcp_var.h tcp.h tcpip.h		\
			udp_var.h udp.h

.include <bsd.kinc.mk>