#	$NetBSD: Makefile,v 1.1.2.2 2009/01/16 22:21:30 bouyer Exp $

.include <bsd.own.mk>

LIB= ldd_aout

# XXX Force one member
SRCS=	dummy.c

LIBISPRIVATE=	yes
.PATH: ${.CURDIR}/..

.include <bsd.lib.mk>
