#	$NetBSD: Makefile,v 1.13 2017/05/21 15:28:37 riastradh Exp $

.include <bsd.own.mk>

SUBDIR+=	ramdisks
SUBDIR+=	.WAIT
#SUBDIR+=	instkernel
#SUBDIR+=	.WAIT
#SUBDIR+=	cdroms
SUBDIR+=	floppies
#SUBDIR+=	liveimage
#SUBDIR+=	installimage
TARGETS+=	release

#iso_image:
#	${MAKEDIRTARGET} cdroms iso_image

#live_image:
	#${MAKEDIRTARGET} liveimage live_image

#install_image:
	#${MAKEDIRTARGET} installimage install_image

.include <bsd.subdir.mk>
