#	@(#)Makefile	8.1 (Berkeley) 6/6/93

.include <bsd.own.mk>

PROG=	w
SRCS=	fmt.c pr_time.c proc_compare.c w.c
MAN1=	w.1 uptime.1
DPADD=	${LIBKVM}
LDADD=	-lkvm
LINKS=	${BINDIR}/w ${BINDIR}/uptime
CPPFLAGS+= -DSUPPORT_UTMP -DSUPPORT_UTMPX

.PATH: ${NETBSDSRCDIR}/bin/ps

COPTS.pr_time.c += -Wno-format-y2k
COPTS.w.c += ${GCC_NO_FORMAT_TRUNCATION}

.include <bsd.prog.mk>
