#!/bin/sh
#
# $NetBSD: maketars,v 1.3.2.5 1997/11/28 08:48:31 mellon Exp $
#
# Make release tar files for some or all lists.  Usage:
# maketars [-arch arch] [-setd setsdir] [-dest destdir] \
#	[-tars tardir] [setname ...]
#

# set defaults
machine=${MACHINE:-`uname -m`}
arch=${MACHINE_ARCH:-`uname -m`}
setd=`pwd`
lists="base comp etc games man misc text"
tars=$RELEASEDIR
dest=$DESTDIR
metalog=

# handle args
while :
do
	case $1 in
	-arch)	
        	arch=$2;
        	shift
        	;;
	-machine)	
        	machine=$2;
        	shift
        	;;
    	-metalog)
        	metalog=$2;
        	shift
        	;;
	-setd)	
        	setd=$2;
        	shift
        	;;
	-dest)	
        	dest=$2;
        	shift
        	;;
	-tars)	
        	tars=$2;
        	shift
        	;;
	-both)	
        	lists="$lists"
        	;;
	-*)	
        	echo "bad option";
        	exit 1
        	;;
	*)	
        	break
        	;;
	esac
	shift
done

[ "$@" ] && lists="$@"

[ "$tars" ] || {
	echo RELEASEDIR must be set
	exit 1
}

[ "$dest" ] || {
	echo DESTDIR must be set
	exit 1
}

if [ -n "$metalog" ]; then
	echo "parsing $metalog"
	(
		cat ${DESTDIR}/etc/mtree/TwoBSD.dist
		echo "/unset all"
		sed -e "s,^\.$dest,.," < $metalog
	) | ${MTREE} -D -k all -N ${DESTDIR}/etc | \
	    sed -e 's,\(.*\) \(\..*\),\2 \1,' > $SDIR/metalog
fi

set -x
for setname in $lists
do
	out=$setname.tar.gz
	echo "making $out"
	sh $setd/makeflist -arch $arch -setd $setd $setname |
	  (cd $dest ; pax -w -d) |
	  gzip -9 > ${tars}/$setname.tgz
done
