#	$NetBSD: Makefile,v 1.235 2021/05/07 21:51:20 nia Exp $
#	from: @(#)Makefile	8.3 (Berkeley) 1/7/94

.include <bsd.own.mk>

SUBDIR= cap_mkdb crunch ctags db genassym gencat hexdump join lex lorder 	\
	m4 make menuc mkdep mklocale mktemp msgc rpcgen sed sortinfo 		\
	stat tic tsort uudecode	vgrind xinstall xlint yacc											

.include <bsd.subdir.mk>
