#	$NetBSD: Makefile,v 1.17 2009/04/10 16:16:12 apb Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/5/93

NOOBJ=	# defined

FILES=	   README connectives hlista hlistb hstop spellhist web2 web2a words
FILESDIR=  ${BINDIR}/dict
LINKS=	   ${FILESDIR}/web2 ${FILESDIR}/words
LINKSMODE= ${FILESMODE}

.include <bsd.prog.mk>