# $FreeBSD$

#.include <bsd.loader.mk>
.include <stand.mk>

#INCSDIR= 		/usr/include/${BOOTSRC}/boot/dloader

SRCS+=			subs.c cmds.c dlogo.c logo_beastie.c logo_fred.c
INCS+=			dloader.h dlogo.h
FILES+= 		${INTERP_MENU} ${INTERP_CONF}

.include <bsd.kinc.mk>