# $FreeBSD$

.include <bsd.loader.mk>

INCSDIR=    /usr/include

SRCS+=			subs.c cmds.c dlogo.c logo_beastie.c logo_fred.c
INCS+=			dloader.h dlogo.h
FILES+= 		${INTERP_MENU} ${INTERP_CONF}

.include <bsd.inc.mk>
