# $NetBSD: Makefile.cdrom,v 1.2.2.3 2007/03/10 19:23:42 riz Exp $

.include <bsd.own.mk>

CDMAKEFSOPTIONS= bootimage=i386; boot/cdboot,no-emul-boot
CDINSTKERNEL=	../../instkernel
CDKERNELS=		twobsd-GENERIC.gz       twobsd
