# $2.11BSD_X44: Makefile.inc,v 1.0 2026/01/20 19:16:45 martin Exp $
# Note: This is required to compile tcsh 

HOSTPROGNAME=	${_TOOL_PREFIX}gethost
HOST_SRCDIR=	contrib/tcsh/bin/gethost

.include "${.CURDIR}/../Makefile.host"
