#	@(#)Makefile	4.2	5/30/85
#

.include <bsd.own.mk>

LIB=		mp
WARNS?=		5

CPPFLAGS+=	-I${.CURDIR}

SRCS= 		pow.c gcd.c msqrt.c mdiv.c mout.c mult.c madd.c util.c
INCSDIR=	/usr/include

.include <bsd.lib.mk>