/*	$OpenBSD: siginfo.h,v 1.14 2024/02/21 15:53:07 deraadt Exp $	*/

/*
 * Copyright (c) 1997 Theo de Raadt
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef _SYS_SIGINFO_H_
#define _SYS_SIGINFO_H_

#include <sys/cdefs.h>

union sigval {
	int		sival_int;	/* integer value */
	void	*sival_ptr;	/* pointer value */
};
typedef union sigval sigval_t;

struct siginfo {
    int 			 si_signo;	/* signal from signal.h */
	int 			 si_code;	/* code from above */
	int				 si_errno;	/* error from errno.h */
	union {
		char		 pad[128];
		struct {
			uid_t 	 uid;
			pid_t 	 pid;
			sigval_t sigval;
			/* child */
			int 	 status;
			clock_t  utime;
			clock_t  stime;
		} proc;
		struct {	/* SIGSEGV, SIGBUS, SIGILL and SIGFPE */
			void	 *addr;		/* faulting address */
			int		 trap;	/* illegal trap number */
		} fault;
	} si_data;

#define si_pad	    si_data.pad
#define si_uid	    si_data.proc.uid
#define si_pid	    si_data.proc.pid
#define si_sigval	si_data.proc.sigval
#define	si_status 	si_data.proc.status
#define	si_utime	si_data.proc.utime
#define	si_stime	si_data.proc.stime
#define si_addr		si_data.fault.addr
#define si_trap		si_data.fault.trap
};
typedef struct siginfo siginfo_t;

/** si_code */
/* SIGILL */
#define	ILL_ILLOPC	1	/* Illegal opcode					*/
#define	ILL_ILLOPN	2	/* Illegal operand					*/
#define	ILL_ILLADR	3	/* Illegal addressing mode			*/
#define	ILL_ILLTRP	4	/* Illegal trap						*/
#define	ILL_PRVOPC	5	/* Privileged opcode				*/
#define	ILL_PRVREG	6	/* Privileged register				*/
#define	ILL_COPROC	7	/* Coprocessor error				*/
#define	ILL_BADSTK	8	/* Internal stack error				*/

/* SIGFPE */
#define	FPE_INTDIV	1	/* Integer divide by zero			*/
#define	FPE_INTOVF	2	/* Integer overflow					*/
#define	FPE_FLTDIV	3	/* Floating point divide by zero	*/
#define	FPE_FLTOVF	4	/* Floating point overflow			*/
#define	FPE_FLTUND	5	/* Floating point underflow			*/
#define	FPE_FLTRES	6	/* Floating point inexact result	*/
#define	FPE_FLTINV	7	/* Invalid Floating point operation	*/
#define	FPE_FLTSUB	8	/* Subscript out of range			*/

/* SIGSEGV */
#define	SEGV_MAPERR	1	/* Address not mapped to object		*/
#define	SEGV_ACCERR	2	/* Invalid permissions for mapped object*/

/* SIGBUS */
#define	BUS_ADRALN	1	/* Invalid address alignment		*/
#define	BUS_ADRERR	2	/* Non-existent physical address	*/
#define	BUS_OBJERR	3	/* Object specific hardware error	*/

/* SIGTRAP */
#define	TRAP_BRKPT	1	/* Process breakpoint			*/
#define	TRAP_TRACE	2	/* Process trace trap			*/
#define	TRAP_EXEC	3	/* Process exec trap			*/
#define	TRAP_CHLD	4	/* Process child trap			*/
#define	TRAP_LWP	5	/* Process lwp trap				*/
#define	TRAP_DBREG	6	/* Process hardware debug register trap	*/
#define	TRAP_SCE	7	/* Process syscall entry trap		*/
#define	TRAP_SCX	8	/* Process syscall exit trap		*/

/* SIGCHLD */
#define	CLD_EXITED	1	/* Child has exited			*/
#define	CLD_KILLED	2	/* Child has terminated abnormally but	*/
						/* did not create a core file		*/
#define	CLD_DUMPED	3	/* Child has terminated abnormally and	*/
						/* created a core file			*/
#define	CLD_TRAPPED	4	/* Traced child has trapped		*/
#define	CLD_STOPPED	5	/* Child has stopped			*/
#define	CLD_CONTINUED	6	/* Stopped child has continued		*/

/* SIGIO */
#define	POLL_IN		1	/* Data input available				*/
#define	POLL_OUT	2	/* Output buffers available			*/
#define	POLL_MSG	3	/* Input message available			*/
#define	POLL_ERR	4	/* I/O Error						*/
#define	POLL_PRI	5	/* High priority input available	*/
#define	POLL_HUP	6	/* Device disconnected				*/

/** si_code */
#define	SI_USER		0	/* Sent by kill(2)						*/
#define	SI_QUEUE	-1	/* Sent by the sigqueue(2)				*/
#define	SI_TIMER	-2	/* Generated by expiration of a timer	*/
						/* set by timer_settime(2)				*/
#define	SI_ASYNCIO	-3	/* Generated by completion of an		*/
						/* asynchronous I/O signal				*/
#define	SI_MESGQ	-4	/* Generated by arrival of a message on	*/
						/* an empty message queue				*/

#ifdef _KERNEL

void siginfo_init(siginfo_t *);
void siginfo_child(struct proc *, int);
void siginfo_trapsignal(int, int, void *, int);
void siginfo_postsig(siginfo_t *, int, int);

#endif /* _KERNEL */
#endif /* _SYS_SIGINFO_H_ */
