#	$211BSD: Makefile,v 1.0 2021/10/28 23:59:27 Exp $

SUBDIR=  ata scsi

INCSDIR= /usr/include/dev/disk

# Only install includes which are used by userland
INCS=	ccd/ccdvar.h md/md.h vnd/vndioctl.h

.include <bsd.kinc.mk>
