#	$211BSD: Makefile,v 1.0 2021/05/25 23:59:27 Exp $

SUBDIR= 	boot

INCSDIR= 	 /usr/include/stand

#.if make(obj) || make(cleandir) || ${MKBOOT} != "no"
#SUBDIR+= stand
#.endif

.include <bsd.kinc.mk>