
.PATH: ${.CURDIR}/ingres/source/iutil

SRCS+=	printup.c resyncpipes.c rdpipe.c proc_error.c copypipes.c 	\
		wrpipe.c prpipe.c getuser.c getnuser.c initucode.c 			\
		initproc.c out_arg.c dblocks.c errfilen.c error.c 			\
		end_job.c ingresname.c printdesc.c paramd.c typeconv.c 		\
		typeunconv.c rub.c cslocks.c rllocks.c pglocks.c 			\
		clr_tuple.c trim_relname.c trbuild.c globals.c 				\
		version.c reset.c
