#
# Copyright (c) 1987 Regents of the University of California.
# All rights reserved.
#
# Redistribution and use in source and binary forms are permitted
# provided that the above copyright notice and this paragraph are
# duplicated in all such forms and that any documentation,
# advertising materials, and other materials related to such
# distribution and use acknowledge that the software was developed
# by the University of California, Berkeley.  The name of the
# University may not be used to endorse or promote products derived
# from this software without specific prior written permission.
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
# WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
#	@(#)Makefile	1.9 (2.11BSD) 1998/1/24
#
MDIR=	/usr/man/cat1
SRCS=	adb.1 addbib.1 apply.1 apropos.1 as.1 at.1 atq.1 atrm.1 \
	awk.1 basename.1 bc.1 biff.1 binmail.1 cal.1 calendar.1 cat.1 \
	cb.1 cc.1 cd.1 checknr.1 chgrp.1 chmod.1 clear.1 cmp.1 col.1 \
	colcrt.1 colrm.1 comm.1 compress.1 cp.1 csh.1 ctags.1 date.1 dc.1 \
	dd.1 deroff.1 df.1 diction.1 diff.1 diff3.1 du.1 echo.1 ed.1 \
	efl.1 eqn.1 error.1 ex.1 expand.1 expr.1 f77.1 false.1 file.1 \
	find.1 fmt.1 fold.1 fpr.1 from.1 fsplit.1 gcore.1 \
	graph.1 grep.1 head.1 hostid.1 indent.1 \
	intro.1 iostat.1 join.1 kill.1 last.1 lastcomm.1 \
	learn.1 leave.1 lex.1 lint.1 lisp.1 ln.1 logger.1 login.1 \
	look.1 lookbib.1 lorder.1 lpq.1 lpr.1 lprm.1 lptest.1 ls.1 \
	lxref.1 m4.1 mail.1 make.1 man.1 mesg.1 mkdep.1 mkdir.1 mkstr.1 \
	more.1 mset.1 msgs.1 mt.1 mv.1 netstat.1 newaliases.1 nice.1 nm.1 
SRCS+=	nroff.1 nslookup.1 od.1 pagesize.1 pdx.1 pi.1 pix.1 \
	plot.1 pmerge.1 pr.1 printenv.1 prof.1 ps.1 ptx.1 pwd.1 px.1 pxp.1 \
	pxref.1 quota.1 ratfor.1 rcp.1 rdist.1 refer.1 rev.1 \
	rlogin.1 rm.1 rmail.1 rmdir.1 roffbib.1 rsh.1 ruptime.1 rwho.1 \
	sccs.1 script.1 sed.1 sendbug.1 sh.1 size.1 sleep.1 soelim.1 \
	sort.1 sortbib.1 spell.1 spline.1 split.1 strcompact.1 strings.1 \
	strip.1 struct.1 style.1 su.1 sum.1 symcompact.1 symorder.1 \
	tabs.1 tail.1 talk.1 \
	tar.1 tbl.1 tc.1 tcopy.1 tee.1 telnet.1 time.1 \
	tip.1 tk.1 tn3270.1 touch.1 tp.1 tr.1 troff.1 true.1 \
	tsort.1 tty.1 ul.1 unifdef.1 uniq.1 units.1 uptime.1 users.1 \
	uucp.1 uuencode.1 uulog.1 uuname.1 uuq.1 uusend.1 uux.1 \
	vacation.1 vgrind.1 vi.1 vmstat.1 vwidth.1 w.1 wait.1 wall.1 wc.1 \
	what.1 whatis.1 which.1 who.1 whois.1 window.1 \
	write.1 xstr.1 yacc.1 yes.1

.include <bsd.man.mk>
.include <bsd.subdir.mk>
