#	$NetBSD: Makefile,v 1.10 2003/09/25 18:05:53 thorpej Exp $

# use 'make -f Makefile.pcidevs' to make pcidevs.h and pcidevs_data.h

INCSDIR= /usr/include/dev/core/pci

# Only install includes which are used by userland
INCS=	pcidevs.h pcidevs_data.h pciio.h pcireg.h 

.include <bsd.kinc.mk>