#
# Copyright (c) 1987 Regents of the University of California.
# All rights reserved.
#
# Redistribution and use in source and binary forms are permitted
# provided that the above copyright notice and this paragraph are
# duplicated in all such forms and that any documentation,
# advertising materials, and other materials related to such
# distribution and use acknowledge that the software was developed
# by the University of California, Berkeley.  The name of the
# University may not be used to endorse or promote products derived
# from this software without specific prior written permission.
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
# WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
#	@(#)Makefile	5.4.3 (2.11BSD GTE) 1996/3/20
#
MDIR=	/usr/man/cat5
SRCS=	L-devices.5 L-dialcodes.5 L.aliases.5 L.cmds.5 L.sys.5 \
	USERFILE.5 a.out.5 acct.5 aliases.5 core.5 dbx.5 \
	dir.5 disktab.5 dtab.5 dump.5 fs.5 fstab.5 gettytab.5 \
	group.5 hosts.5 map3270.5 networks.5 passwd.5 \
	phones.5 plot.5 printcap.5 protocols.5 remote.5 resolver.5 \
	services.5 shells.5 stack.5 tar.5 termcap.5 tp.5 ttys.5 types.5 \
	syserrlst.5 \
	tzfile.5 utmp.5 uuencode.5 vfont.5 vgrindefs.5

.include <bsd.man.mk>
.include <bsd.subdir.mk>
