#
# Copyright (c) 1980 Regents of the University of California.
# All rights reserved.  The Berkeley software License Agreement
# specifies the terms and conditions for redistribution.
#
#	@(#)Makefile	5.4.1 (2.11BSD) 1996/1/11
#

# Programs that live in subdirectories, and have makefiles of their own.
#

SUBDIR=		libarch libc libkern

SUBDIR+=	csu/${MACHINE}

.include <bsd.subdir.mk>