#
# Copyright (c) 1980 Regents of the University of California.
# All rights reserved.  The Berkeley software License Agreement
# specifies the terms and conditions for redistribution.
#
#	@(#)Makefile	5.4.1 (2.11BSD) 1996/1/11
#

# Programs that live in subdirectories, and have makefiles of their own.
# 
# To stay in keeping with 2.11BSD: All libs are in usr.lib
# Excluding csu, libarch, libc, libcompat & libkern

.include <bsd.own.mk>

SUBDIR=	csu libarch libc libcompat libelftc libkern

.include <bsd.subdir.mk>