#	$NetBSD: Makefile,v 1.3 2010/12/12 04:06:19 christos Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}awk
HOST_SRCDIR=	contrib/nawk/bin
HOST_CPPFLAGS+=	-D__EXTENSIONS__	# for isblank

.include "${.CURDIR}/../Makefile.host"
