#	$NetBSD: Makefile,v 1.13 2019/06/04 15:07:55 hannken Exp $
#

INCS=		auth_unix.h auth.h clnt.h pmap_clnt.h pmap_prot.h pmap_rmt.h \
			rpc_msg.h rpc.h svc_auth.h svc.h types.h xdr.h 

INCSDIR=	/usr/include/rpc

.include <bsd.rpc.mk>
.include <bsd.prog.mk>