#
# Public Domain.  1996/6/25 - Steven Schultz
#
#	@(#)Makefile	1.0 (2.11BSD GTE) 1996/6/25
#

.include <bsd.own.mk>

LIB=		stubs
WARNS?=		5

CPPFLAGS+=	-I${.CURDIR}

SRCS=		cmds.c stubs.c stubtest.c

.include <bsd.lib.mk>
