#	$NetBSD: Makefile,v 1.2 1998/10/12 19:50:09 bouyer Exp $

INCSDIR= /usr/include/dev/disk/scsi

# Only install includes which are used by userland
INCS=	scsi_all.h scsi_disk.h scsiconf.h

.include <bsd.kinc.mk>
