#	$NetBSD: Makefile,v 1.4 2001/05/31 21:54:07 tron Exp $

INCSDIR= /usr/include/dev/disk/scsi

# Only install includes which are used by userland
INCS=	scsipi_all.h scsi_all.h scsipi_cd.h scsipi_debug.h scsi_disk.h 	\
		scsipiconf.h scsiconf.h ses.h

.include <bsd.kinc.mk>
