#	$211BSD: Makefile,v 1.0 2021/08/11 20:20:01 thorpej Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}boot0cfg
HOST_SRCDIR=	usr.sbin/boot0cfg
HOST_SRCS=		disklabel.c

.include "${.CURDIR}/../Makefile.nbincludes"
.include "${.CURDIR}/../Makefile.host"

.PATH: ${.CURDIR}/../../lib/libc/gen