#	$NetBSD: Makefile,v 1.5.2.1 1997/11/13 02:40:14 thorpej Exp $
#	from @(#)Makefile	8.1 (Berkeley) 6/5/93

# Missing:  ms

#SUBDIR=	dict doc man me misc mk skel tabset termcap tmac zoneinfo
SUBDIR= adb font font fontinfo learn lint me misc mk ms pascal tabset term termcap tmac zoneinfo
.include <bsd.subdir.mk>
