#	from @(#)Makefile	8.1 (Berkeley) 6/5/93

.include <bsd.own.mk>

.include 	"/usr/man/Makefile.inc"

SUBDIR= 	adb font font fontinfo learn lint me misc mk ms pascal tabset term termcap tmac zoneinfo

.include <bsd.subdir.mk>
