#
# Copyright (c) 1987 Regents of the University of California.
# All rights reserved.
#
# Redistribution and use in source and binary forms are permitted
# provided that the above copyright notice and this paragraph are
# duplicated in all such forms and that any documentation,
# advertising materials, and other materials related to such
# distribution and use acknowledge that the software was developed
# by the University of California, Berkeley.  The name of the
# University may not be used to endorse or promote products derived
# from this software without specific prior written permission.
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
# WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
#	@(#)Makefile	5.4.15 (2.11BSD) 1997/12/8
#
MDIR=	/usr/man/cat3
SRCS=	abort.3 abs.3 alarm.3 asinh.3 assert.3 atof.3 bstring.3 byteorder.3 \
	compat-sys5.3 crypt.3 ctime.3 ctype.3 curses.3 dbm.3 daemon.3 \
	devname.3 directory.3 ecvt.3 end.3 erf.3 err.3 execl.3 exit.3 \
	exp.3 fclose.3 ferror.3 floor.3 \
	fopen.3 fread.3 frexp.3 fseek.3 getc.3 getdisk.3 getenv.3 getfsent.3 \
	getgrent.3 gethostbyname.3 getnetent.3 getopt.3 getpass.3 \
	getgrouplist.3 getloadavg.3 getmntinfo.3 getsubopt.3 \
	getprotoent.3 getpwent.3 gets.3 getservent.3 getttyent.3 \
	getusershell.3 getwd.3 hypot.3 ieee.3 inet.3 infnan.3 initgroups.3 
SRCS+=	insque.3 intro.3 j0.3 l3tol.3 ldfps.3 lgamma.3 lib2648.3 \
	malloc.3 math.3 mktemp.3 monitor.3 mp.3 ndbm.3 nice.3 nlist.3 ns.3 \
	pause.3 perror.3 plot.3 popen.3 printf.3 psignal.3 putc.3 puts.3 \
	qsort.3 rand.3 random.3 rcmd.3 regex.3 resolver.3 rexec.3 scandir.3 \
	scanf.3 setbuf.3 setjmp.3 siginterrupt.3 signal.3 sin.3 \
	sinh.3 sleep.3 sqrt.3 stdio.3 strftime.3 string.3 strtok.3 stty.3 \
	setmode.3 setruid.3 sigsetops.3 \
	strcspn.3 strpbrk.3 strsep.3 strspn.3 strtol.3 strtoul.3 strstr.3 \
	swab.3 sysctl.3 syslog.3 \
	system.3 termcap.3 time.3 times.3 ttyname.3 ualarm.3 uname.3 ungetc.3 \
	syserrlst.3 \
	utime.3 valloc.3 varargs.3
	
.include <bsd.man.mk>
.include <bsd.subdir.mk>
