#	$NetBSD: Makefile,v 1.13 1996/10/02 16:19:51 ws Exp $

.include <bsd.own.mk>

# Temporary location (Will be defined in stand for each machine arch)
SA_LOADER_INTERP_NAME= dloader  # Bootloader Interpreter name (Options: dloader only atm)
SA_LOADER_INTERP= no            # Use Bootloader Interpreter (Will likely default to yes)
SA_USE_BCACHE= no               # Machine-dependent: use bcache
SA_USE_ISABUS= no               # Machine-dependent: use isabus plug-in play
SA_USE_PNP= no                  # Machine-dependent: use plug-in play

SAMISCMAKEFLAGS+= ${SA_INCLUDE_NET} ${SA_USE_LOADFILE} ${SA_ENABLE_BIENDIAN}
SAMISCMAKEFLAGS+= ${SA_LOADER_INTERP} ${SA_USE_BCACHE} ${SA_USE_ISABUS} ${SA_USE_PNP}
CPPFLAGS=	-I${SADIR} ${SACPPFLAGS} ${SAMISCCPPFLAGS} -DCOMPAT_UFS ${DEBUGCPPFLAGS}

.PATH.c: 	${SADIR} \
            ${.PARSEDIR}/../../../lib/libc/stdlib \
            ${.PARSEDIR}/../../../lib/libc/string

# stand routines
SRCS+=	alloc.c bcopy.c bzero.c errno.c getfile.c 		\
		gets.c globals.c panic.c printf.c snprintf.c 	\
		strdup.c strspn.c strtol.c twiddle.c 			\
		zalloc_malloc.c zalloc.c

SRCS+= environment.c getopt.c pager.c panic.c

# io routines
SRCS+= 	closeall.c dev.c disklabel.c ioctl.c ls.c stat.c
SRCS+=	close.c lseek.c open.c read.c write.c

# filesystems
SRCS+=	lfs.c ufs.c cd9660.c ustarfs.c dosfs.c

.if (${SA_USE_LOADFILE} == "yes")
SRCS+=	loadfile.c loadfile_ecoff.c loadfile_elf32.c loadfile_elf64.c lookup_elf32.c loadfile_xcoff32.c loadfile_xcoff64.c
.if (${MACHINE_CPU} != "mips")
SRCS+=	loadfile_aout.c
.endif
.endif

.if (${SA_INCLUDE_NET} == "yes")
# network routines
SRCS+=	arp.c ether.c ether_sprintf.c in_cksum.c net.c netif.c rpc.c udp.c

# network info services:
SRCS+=	bootp.c rarp.c bootparam.c

# boot filesystems
SRCS+=	nfs.c tftp.c
.endif

.if (${SA_ENABLE_BIENDIAN} == "yes")
CPPFLAGS+=	-DLIBSA_BIENDIAN_SUPPORT
SRCS+=	byteorder.c
.endif

.if (${SA_LOADER_INTERP} == "yes")
SRCS+= interp_backslash.c interp_parse.c interp.c   # still in stand/boot/common
SRCS+= interp_${SA_LOADER_INTERP_NAME}.c            # still in stand/boot/common
.if (${SA_LOADER_INTERP_NAME} != "dloader")
# include interpreter related files if any ??
.else
.error Unknown interpreter ${SA_LOADER_INTERP_NAME}
.endif
.endif

.if (${SA_USE_BCACHE} == "yes")
SRCS+= bcache.c # still in stand/boot/common
.endif

.if (${SA_USE_ISABUS} == "yes")
SRCS+= isapnp.c # still in stand/boot/common
.endif

.if (${SA_USE_PNP} == "yes")
SRCS+= pnp.c    # still in stand/boot/common
.endif

#.include <bsd.lib.mk>

lib${LIB}.o:: ${OBJS:O} __buildstdlib

CPPFLAGS+=	-Wno-pointer-sign

.if defined(HAVE_GCC) && ${MACHINE_ARCH} == "vax"
COPTS.bootp.c+=	-O0
.endif

# Files to clean up
CLEANFILES+= lib${LIB}.o lib${LIB}.po

# Remove from SRCS the .c files for any .S files added by the MD makefiles,
# also remove from SRCS the .c files for the .c files in NO_SRCS.
# (Unlike libc, we don't worry about lint)

.for check_file in ${SRCS:M*.S} ${NO_SRCS}
unwanted_file := ${SRCS:M${check_file:.S=.c}}
.if "${unwanted_file}" != ""
SRCS := ${SRCS:N${unwanted_file}}
.endif

.endfor
