#
# Copyright (c) 1987 Regents of the University of California.
# All rights reserved.
#
# Redistribution and use in source and binary forms are permitted
# provided that the above copyright notice and this paragraph are
# duplicated in all such forms and that any documentation,
# advertising materials, and other materials related to such
# distribution and use acknowledge that the software was developed
# by the University of California, Berkeley.  The name of the
# University may not be used to endorse or promote products derived
# from this software without specific prior written permission.
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
# WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
#	@(#)Makefile	5.4.1 (2.11BSD) 1996/01/26
#
MDIR=	/usr/man/cat3f
SRCS=	abort.3f access.3f alarm.3f bessel.3f bit.3f chdir.3f chmod.3f etime.3f \
	exit.3f fdate.3f flmin.3f flush.3f fork.3f fseek.3f getarg.3f getc.3f \
	getcwd.3f getenv.3f getlog.3f getpid.3f getuid.3f hostnm.3f idate.3f \
	index.3f intro.3f ioinit.3f kill.3f link.3f loc.3f long.3f malloc.3f \
	perror.3f plot.3f putc.3 qsort.3f rand.3f random.3f rename.3f signal.3f \
	sleep.3f stat.3f system.3f time.3f topen.3f traper.3f trapov.3f trpfpe.3f \
	ttynam.3f unlink.3f wait.3f

.include <bsd.man.mk>
.include <bsd.subdir.mk>
