#
# Copyright (c) 1987 Regents of the University of California.
# All rights reserved.
#
# Redistribution and use in source and binary forms are permitted
# provided that the above copyright notice and this paragraph are
# duplicated in all such forms and that any documentation,
# advertising materials, and other materials related to such
# distribution and use acknowledge that the software was developed
# by the University of California, Berkeley.  The name of the
# University may not be used to endorse or promote products derived
# from this software without specific prior written permission.
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
# WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
#	@(#)Makefile	5.4.1 (2.11BSD) 1996/01/26
#
MDIR=	/usr/man/cat3f
SRCS=	abort.3 access.3 alarm.3 bessel.3 bit.3 chdir.3 chmod.3 etime.3 \
	exit.3 fdate.3 flmin.3 flush.3 fork.3 fseek.3 getarg.3 getc.3 \
	getcwd.3 getenv.3 getlog.3 getpid.3 getuid.3 hostnm.3 idate.3 \
	index.3 intro.3 ioinit.3 kill.3 link.3 loc.3 long.3 malloc.3 \
	perror.3 plot.3 putc.3 qsort.3 rand.3 random.3 rename.3 signal.3 \
	sleep.3 stat.3 system.3 time.3 topen.3 traper.3 trapov.3 trpfpe.3 \
	ttynam.3 unlink.3 wait.3

.include <bsd.man.mk>
.include <bsd.subdir.mk>
