#
# Copyright (c) 1983 Regents of the University of California.
# All rights reserved.  The Berkeley software License Agreement
# specifies the terms and conditions for redistribution.
#
#	@(#)Makefile	5.12.3 (2.11BSD GTE) 1996/12/13
#

.include <bsd.own.mk>

SUBDIR=	libF77 libI77 libU77

.include <bsd.subdir.mk>
