#
# Public domain - 1996/10/21 - sms
#
#	@(#)Makefile	1.2 (2.11BSD) 1996/11/16
#
#  Makefile for misc data files (lib.b from 'bc', usw.)
#

FILES= 	eign lib.b Mail.help Mail.tildehelp units gprof.callg gprof.flat \
 	vlpmacs mkproto.data
FILESDIR=${BINDIR}/misc

.include <bsd.prog.mk>
