#	$211BSD: Makefile,v 1.0 2021/08/11 20:20:01 thorpej Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}btxld
HOST_SRCDIR=	usr.sbin/btxld

.include "${.CURDIR}/../Makefile.nbincludes"
.include "${.CURDIR}/../Makefile.host"