#
# Copyright (c) 1980 Regents of the University of California.
# All rights reserved.  The Berkeley software License Agreement
# specifies the terms and conditions for redistribution.
#
#	@(#)Makefile	5.5 (Berkeley) 4/25/86
#

# Makefile for f77 I/O lib, libI77.a

.include <bsd.own.mk>

LIB=    libI77

SRCS=   backspace.c \
		c_dfe.c \
		c_iio.c \
		c_sfe.c \
		close.c \
		dofio.c \
		dolio.c \
		douio.c \
		due.c \
		endfile.c \
		err.c \
		f77_abort.c \
		f_errlist.c \
		fmt.c \
		fmtlib.c \
		inquire.c \
		lread.c \
		lwrite.c \
		open.c \
		rdfe.c \
		rdfmt.c \
		rewind.c \
		rfi.c \
		rsfe.c \
		rsli.c \
		rsnmle.c \
		sue.c \
		util.c \
		wdfe.c \
		wfi.c \
		wrtfmt.c \
		wsfe.c \
		wsli.c \
		wsnmle.c

.include <bsd.lib.mk>
