#
# Public Domain.  1996/6/25 - Steven Schultz
#
#	@(#)Makefile	1.0 (2.11BSD GTE) 1996/6/25
#

.include <bsd.own.mk>

PROG= 	ctimed
SRCS=	ctimed.c
BINDIR=	/usr/libexec

BINOWN=		root
BINMODE=	755

.include <bsd.prog.mk>