#	$211BSD: Makefile,v 1.0 2023/08/06 23:59:27 Exp $

INCSDIR= 	/usr/include/nfs

INCS=	nfs.h nfsdiskless.h nfsm_subs.h nfsmount.h nfsnode.h 	\
		nfsproto.h nfsrtt.h nfsrvcache.h nqnfs.h rpcv2.h 		\
		xdr_subs.h

.include <bsd.kinc.mk>