#	$NetBSD: Makefile,v 1.2 1999/01/06 12:24:51 drochner Exp $

INCSDIR= /usr/include/dev/misc/pccons

INCS= pcdisplay.h pcdisplayvar.h pckbcvar.h pckbdreg.h pckbdvar.h pckbportvar.h \
	pmsreg.h wskbdmap_mfii.h

.include <bsd.kinc.mk>
