#	$NetBSD: Makefile,v 1.3 2008/04/23 09:57:59 plunky Exp $

INCSDIR= /usr/include/netiso

INCS=	argo_debug.h clnl.h clnp.h clnp_stat.h cltp_var.h 		\
		eonvar.h esis.h idrp_var.h iso.h iso_errno.h iso_pcb.h 	\
		iso_snpac.h iso_var.h tp_iso.h

.include <bsd.kinc.mk>