#	$NetBSD: Makefile,v 1.3 2008/04/23 09:57:59 plunky Exp $

SUBDIR= tp_proto

INCSDIR= /usr/include/netiso

INCS=	argo_debug.h clnl.h clnp.h clnp_stat.h cltp_var.h cons.h cons_pcb.h \
	    eonvar.h esis.h idrp_var.h iso.h iso_errno.h iso_pcb.h iso_snpac.h \
	    iso_var.h tp_clnp.h tp_events.h tp_meas.h tp_param.h tp_pcb.h \
	    tp_protosw.h tp_seq.h tp_stat.h tp_states.h tp_timer.h tp_tpdu.h \
        tp_tpdu_f.h tp_tpdu_v.h tp_trace.h tp_user.h tp_var.h tuba_table.h

.include <bsd.kinc.mk>
