#	$NetBSD: Makefile,v 1.6.2.1.2.2 2005/05/13 20:47:11 riz Exp $

INCSDIR= /usr/include/netccitt

INCS=   dll.h hd_var.h hdlc.h llc_var.h pk.h pk_extern.h pk_var.h x25.h \
	    x25acct.h x25err.h

.include <bsd.kinc.mk>
