#	$211BSD: Makefile,v 1.0 2021/05/25 23:59:27 Exp $

INCSDIR= 	/usr/include/net

INCS=		af.h bpf_compat.h bpf.h bpfdesc.h if_arp.h 	\
			if_slvar.h if.h netisr.h radix.h raw_cb.h	\
			route.h

.include <bsd.kinc.mk>