#	$211BSD: Makefile,v 1.0 2021/05/25 23:59:27 Exp $

INCSDIR= 	/usr/include/ufs/ufs211

INCS= 		ufs211_dir.h ufs211_extern.h ufs211_fs.h ufs211_inode.h ufs211_mount.h ufs211_quota.h

.include <bsd.kinc.mk>