#	$211BSD: Makefile,v 1.0 2021/05/25 23:59:27 Exp $

INCSDIR= 	/usr/include/netns

INCS=		idp_var.h idp.h ns_error.h ns_if.h ns_pcb.h			\
			ns.h sp.h spidp.h spp_debug.h spp_timer.h spp_var.h
			
.include <bsd.kinc.mk>