# $FreeBSD: src/sys/boot/Makefile,v 1.18 2003/08/16 02:48:20 obrien Exp $

SUBDIR= 	arch common dloader #efi fdt uboot

INCSDIR= 	/usr/include/stand/boot

INCSYMLINKS= sys/lib/libsa	/usr/include/stand/libsa

.include <bsd.kinc.mk>
		
