#
# Copyright (c) 1987 Regents of the University of California.
# All rights reserved.
#
# Redistribution and use in source and binary forms are permitted
# provided that the above copyright notice and this paragraph are
# duplicated in all such forms and that any documentation,
# advertising materials, and other materials related to such
# distribution and use acknowledge that the software was developed
# by the University of California, Berkeley.  The name of the
# University may not be used to endorse or promote products derived
# from this software without specific prior written permission.
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
# WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
#	@(#)Makefile	2.11 (2.11BSD) 2000/3/4
#
MDIR=	/usr/man/cat2
SRCS=	accept.2 access.2 acct.2 adjtime.2 bind.2 brk.2 chdir.2 chmod.2 \
	chown.2 chroot.2 close.2 connect.2 creat.2 dup.2 execve.2 exit.2 \
	chflags.2 \
	fcntl.2 fetchi.2 flock.2 fork.2 fperr.2 fsync.2 getdtablesize.2 \
	getgroups.2 gethostid.2 gethostname.2 getitimer.2 \
	getpagesize.2 getpeername.2 getpgrp.2 getpid.2 getpriority.2 \
	getrlimit.2 getrusage.2 getsockname.2 getsockopt.2 gettimeofday.2 \
	getfsstat.2 getlogin.2 \
	getuid.2 setreuid.2 setuid.2 getgid.2 setregid.2 \
	intro.2 ioctl.2 kill.2 killpg.2 link.2 listen.2 \
	lock.2 lseek.2 mkdir.2 mknod.2 mount.2 nostk.2 open.2 phys.2 \
	pipe.2 profil.2 ptrace.2 quota.2 read.2 readlink.2 reboot.2 \
	recv.2 rename.2 rmdir.2 select.2 send.2 setgroups.2 setpgrp.2 \
	setquota.2 shutdown.2 sigblock.2 sigpause.2 \
	sigaction.2 sigaltstack.2 sigpending.2 sigprocmask.2 sigsuspend.2 \
	sigreturn.2 sigsetmask.2 sigstack.2 sigwait.2 sigvec.2 socket.2 \
	socketpair.2 \
	stat.2 statfs.2 swapon.2 symlink.2 sync.2 syscall.2 truncate.2 ucall.2 \
	umask.2 unlink.2 utimes.2 vfork.2 vhangup.2 wait.2 write.2

.include <bsd.man.mk>
.include <bsd.subdir.mk>
