#	$NetBSD: Makefile,v 1.2 1998/10/12 19:50:09 bouyer Exp $

INCSDIR= /usr/include/dev/disk/ata

# Only install includes which are used by userland
INCS=	atareg.h atavar.h satareg.h

.include <bsd.kinc.mk>
